### ISSUE TITLE
Testing results don't match the original room data.

### ISSUE THREAD

**Issue by Hao-FANG-92** [qianguih/RSNet#2]
Hi, qian gui

Thanks for the share of this excellent work and it's really nice!  I have some questions on the testing results on Area5.

Actually, the visualization results in folder ./results, i.e. Area_5_conferenceRoom_1_gt seems like a different room with the RAW_DATA/Area5/conferenceRoom_1. It's the same case for the other rooms.

Do you have idea about that?

**Comment by qianguih** [comment]
thanks for pointing this out. Yes, there is a mismatch in the file name. our internal version works fine. I am hunting potential bugs to fix this. will be fixed in next commit.

**Comment by Hao-FANG-92** [comment]
Hi, qian gui

I think the bug is in line 54 and 55 of file load_data.py, where the return list of h5 files are not odered.  Change it as:
        train_files = sorted(glob.glob(TRAIN_DIR + '*.h5'))
        test_files = sorted(glob.glob(TEST_DIR + '*.h5'))
and the problem is fixed.

Thanks for your time.

**Comment by tonysy** [comment]
@Hao-FANG-92  Hi, could you share the solution to visualize the .obj file ? I'm new to 3D vision and not familiar with this. Thanks a lot.

**Comment by iSarmad** [comment]
Hi these obj files cannot be visualized using Obj file viewers available, there is something wrong with the files generated by the code. Can you tell how you visualize these files ? thanks

**Comment by longmalongma** [comment]
> Hi, qian gui
> 
> Thanks for the share of this excellent work and it's really nice! I have some questions on the testing results on Area5.
> 
> Actually, the visualization results in folder ./results, i.e. Area_5_conferenceRoom_1_gt seems like a different room with the RAW_DATA/Area5/conferenceRoom_1. It's the same case for the other rooms.
> 
> Do you have idea about that?

Hi,when I try to run your code,I find I can not compile your slice_pool_layer and slice_unpool_layer,can you send me your files have compiled files?my email is that:1442342449@qq.com.looking forward your reply

**Comment by longmalongma** [comment]
> .obj fil

meshlab is ok.

**Comment by MCemGunes** [comment]
Hello all, sorted() Method worked on my local machine but I still got mixed results on the HPC server. I don't know the exact problem but it might be multiprocessing or a similar thing. Not sure but, it is not that important. 

I want to share my solution in case of anyone faces a similar problem.

We can use the number of the *ply_data_all_*.h5 files to sort the files directly. * might be  1,2,...,29,215,... basically any integer.  

Simply, we normalize the path which means we transform it into a string (it is optional). Then we split the text using the "_" characters and choose the last part (ie. 223.h5 ).  Finally, we split the chunk we have into two using the "." character and pick the first part. I use my custom dataset so the naming convention might vary. The main idea is sorted() function alone is error-prone however, you can be sure you use the right order by adding a key that sorts integers inside the name directly. If you wish you can implement the key inside the first sorted() methods.

The solution adapted from [this ](https://stackoverflow.com/questions/33159106/sort-filenames-in-directory-in-ascending-order)post.

```
train_files = sorted(train_files, key=lambda x: int(  (os.path.normpath(x).split("_"))[-1].split(".")[0]  ))
test_files = sorted(test_files, key=lambda x: int(  (os.path.normpath(x).split("_"))[-1].split(".")[0]  ))
```
